default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWD'] %>
  pool: 5
  port: <%= ENV['PG_PORT'] %>
  timeout: 5000
  host: <%= ENV['PG_HOST'] %>

development:
  <<: *default
  database: <%= ENV['PG_DB'] %>

test:
  <<: *default
  database: <%= ENV['PG_DB'] %>

production:
  <<: *default
  database: <%= ENV['PG_DB'] %>
